---
# Template separado para Auto Scaling Group (puede usarse de forma independiente)
AWSTemplateFormatVersion: '2010-09-09'
Description: Auto Scaling Group con Launch Template, Warm Pool y Scheduled Actions

Parameters:
  MinticAmiId:
    Description: AMI para las instancias EC2
    Type: String
    Default: ami-0f88e80871fd81e91

  VPCId:
    Description: ID de la VPC donde se creara el ASG
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: Lista de Subnets para el ASG
    Type: List<AWS::EC2::Subnet::Id>

  SecurityGroupId:
    Description: ID del Security Group para las instancias
    Type: AWS::EC2::SecurityGroup::Id

  TargetGroupArn:
    Description: ARN del Target Group del ALB (opcional)
    Type: String
    Default: ""

Conditions:
  HasTargetGroup: !Not [!Equals [!Ref TargetGroupArn, ""]]

Resources:

  # Plantilla de lanzamiento para el Auto Scaling Group
  MinticLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MinticASGLaunchTemplate
      LaunchTemplateData:
        ImageId: !Ref MinticAmiId
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref SecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            
            # Obtener metadata de la instancia
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
            AZ=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            
            echo "<html><body>" > /var/www/html/index.html
            echo "<h1>Hola desde CloudFormation ASG!</h1>" >> /var/www/html/index.html
            echo "<p>Instancia: $INSTANCE_ID</p>" >> /var/www/html/index.html
            echo "<p>Zona de Disponibilidad: $AZ</p>" >> /var/www/html/index.html
            echo "</body></html>" >> /var/www/html/index.html
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: MinticASG-Instance
              - Key: Environment
                Value: Production
              - Key: ManagedBy
                Value: CloudFormation

  # Auto Scaling Group con 4 instancias distribuidas en 2 AZ
  MinticASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: MinticAutoScalingGroup
      VPCZoneIdentifier: !Ref SubnetIds
      LaunchTemplate:
        LaunchTemplateId: !Ref MinticLaunchTemplate
        Version: !GetAtt MinticLaunchTemplate.LatestVersionNumber
      MinSize: '4'
      MaxSize: '6'
      DesiredCapacity: '4'
      TargetGroupARNs: !If
        - HasTargetGroup
        - - !Ref TargetGroupArn
        - !Ref AWS::NoValue
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: MinticASG-Instance
          PropagateAtLaunch: true
        - Key: Environment
          Value: Production
          PropagateAtLaunch: true

  # Apaga todas las instancias del ASG a las 8:00 AM hora Colombia (13:00 UTC)
  MinticASGStopSchedule:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref MinticASG
      DesiredCapacity: 0
      MinSize: 0
      Recurrence: "0 13 * * *"

  # Enciende todas las instancias del ASG a las 8:15 AM hora Colombia (13:15 UTC)
  MinticASGStartSchedule:
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref MinticASG
      DesiredCapacity: 4
      MinSize: 4
      Recurrence: "15 13 * * *"

  # Warm pool para mantener 2 instancias "listas" pero detenidas
  MinticWarmPool:
    Type: AWS::AutoScaling::WarmPool
    Properties:
      AutoScalingGroupName: !Ref MinticASG
      PoolState: Stopped
      MinSize: 2
      MaxGroupPreparedCapacity: 4

  # Politica de escalado basada en CPU
  MinticScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref MinticASG
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70.0

Outputs:
  ASGName:
    Description: Nombre del Auto Scaling Group
    Value: !Ref MinticASG

  LaunchTemplateId:
    Description: ID del Launch Template
    Value: !Ref MinticLaunchTemplate

  LaunchTemplateVersion:
    Description: Version del Launch Template
    Value: !GetAtt MinticLaunchTemplate.LatestVersionNumber
