---
AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance que despliega una aplicacion web desde S3 (compatible con VPC)

Parameters:
  MinticAmiId:
    Description: AMI para las instancias EC2
    Type: String
    Default: ami-0f88e80871fd81e91

  VPCId:
    Description: ID de la VPC donde se creara la instancia (dejar vacio para VPC default)
    Type: String
    Default: ""

  SubnetId:
    Description: ID de la Subnet donde se creara la instancia (dejar vacio para subnet default)
    Type: String
    Default: ""

  S3BucketName:
    Description: Nombre del bucket S3 con la aplicacion
    Type: String
    Default: ""

  ZipFileName:
    Description: Nombre del archivo ZIP en S3
    Type: String
    Default: "AWS-PROJECT-TEST.zip"

Conditions:
  UseVPC: !Not [!Equals [!Ref VPCId, ""]]
  UseSubnet: !Not [!Equals [!Ref SubnetId, ""]]
  HasS3Bucket: !Not [!Equals [!Ref S3BucketName, ""]]

Resources:
  # Security Group con soporte para VPC
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso HTTP y SSH desde cualquier lugar
      VpcId: !If [UseVPC, !Ref VPCId, !Ref "AWS::NoValue"]
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: Permitir trafico HTTP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          Description: Permitir acceso SSH
      Tags:
        - Key: Name
          Value: MinTic EC2 Web Security Group

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !If
                    - HasS3Bucket
                    - !Sub 'arn:aws:s3:::${S3BucketName}'
                    - !Sub 'arn:aws:s3:::mintic-bucket-${AWS::AccountId}-${AWS::Region}'
                  - !If
                    - HasS3Bucket
                    - !Sub 'arn:aws:s3:::${S3BucketName}/*'
                    - !Sub 'arn:aws:s3:::mintic-bucket-${AWS::AccountId}-${AWS::Region}/*'
      Tags:
        - Key: Name
          Value: MinTic EC2 Web Role

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # Instancia EC2 con soporte para VPC
  EC2WebInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref MinticAmiId
      InstanceType: t2.micro
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces: !If
        - UseSubnet
        - - AssociatePublicIpAddress: true
            SubnetId: !Ref SubnetId
            DeviceIndex: 0
            GroupSet:
              - !Ref EC2SecurityGroup
        - !Ref "AWS::NoValue"
      SecurityGroups: !If
        - UseSubnet
        - !Ref "AWS::NoValue"
        - - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            # =====================================================
            # SCRIPT DE DESPLIEGUE AUTOMATICO DESDE S3 HACIA EC2
            # Descripcion:
            #   - Instala dependencias
            #   - Descarga y despliega aplicacion desde S3
            #   - Registra logs locales y en S3
            # =====================================================

            # Archivo de log local
            LOG_FILE="/var/log/deploy.log"
            exec > >(tee -a "$LOG_FILE") 2>&1

            echo "===== INICIO DEL DESPLIEGUE ====="

            # Actualiza el sistema e instala dependencias
            echo "Actualizando sistema e instalando dependencias..."
            yum update -y
            yum install -y httpd aws-cli unzip

            # Inicia y habilita Apache
            echo "Iniciando servicio Apache..."
            systemctl enable httpd
            systemctl start httpd

            # Configuracion del bucket y archivo
            BUCKET="${BucketName}"
            ZIPFILE="${ZipFileName}"
            DEST="/var/www/html"

            echo "Bucket configurado: $BUCKET"
            echo "Archivo a desplegar: $ZIPFILE"

            # Descargar archivo ZIP desde S3
            echo "Descargando $ZIPFILE desde S3..."
            aws s3 cp s3://$BUCKET/$ZIPFILE /tmp/$ZIPFILE

            # Verificar si la descarga fue exitosa
            if [ ! -f /tmp/$ZIPFILE ]; then
                echo "ERROR: No se pudo descargar el archivo $ZIPFILE desde S3."
                echo "<html><body><h1>Hola desde EC2 Web - Despliegue Basico</h1></body></html>" > $DEST/index.html
            else
                # Descomprimir en la raiz del servidor web
                echo "Descomprimiendo archivo..."
                unzip -o /tmp/$ZIPFILE -d $DEST

                # Si el ZIP contiene una carpeta 'eliza', mueve su contenido
                if [ -d "$DEST/eliza" ]; then
                    echo "Reorganizando estructura del proyecto..."
                    mv $DEST/eliza/* $DEST/
                    rm -rf $DEST/eliza
                fi
            fi

            # Ajustar permisos para Apache
            echo "Ajustando permisos..."
            chown -R apache:apache $DEST
            find $DEST -type d -exec chmod 755 {} \;
            find $DEST -type f -exec chmod 644 {} \;

            # Obtener token IMDSv2 para metadata
            echo "Obteniendo metadata de la instancia..."
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" \
                -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

            INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)
            PRIVATE_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/local-ipv4)
            PUBLIC_IP=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/public-ipv4)
            FECHA=$(date +"%Y-%m-%d_%H-%M-%S")

            # Crear archivo de estado visible en el sitio web
            echo "Creando archivo de estado en el sitio web..."
            cat <<EOF > $DEST/status.txt
            <h2>Aplicacion desplegada correctamente desde S3 ($ZIPFILE)</h2>
            <p>Fecha de despliegue: $FECHA</p>
            <p>Instancia: $INSTANCE_ID</p>
            <p>IP Publica: $PUBLIC_IP</p>
            <p>IP Privada: $PRIVATE_IP</p>
            EOF

            # Subir log a S3 dentro de la carpeta logs (si el bucket existe)
            echo "Subiendo log a S3..."
            aws s3 cp /tmp/deploy-log.txt s3://$BUCKET/logs/deploy_$INSTANCE_ID_$FECHA.txt 2>/dev/null || true

            echo "===== DESPLIEGUE FINALIZADO CON EXITO ====="
          - BucketName: !If
              - HasS3Bucket
              - !Ref S3BucketName
              - !Sub 'mintic-bucket-${AWS::AccountId}-${AWS::Region}'
      Tags:
        - Key: Name
          Value: MinTic EC2 Web Instance

Outputs:
  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref EC2WebInstance
  PublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2WebInstance.PublicIp
  WebsiteURL:
    Description: URL to access the deployed website
    Value: !Sub http://${EC2WebInstance.PublicIp}
